name: Run Selenium Tests in Firefox

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Firefox and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox xvfb

      - name: Set up stable GeckoDriver
        run: |
          GECKODRIVER_VERSION="v0.33.0"  # Stabil version
          wget "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
          tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Start Xvfb (Virtual Display)
        run: |
          Xvfb :99 -ac -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install dependencies
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test
